package com.mhexpenses.bangla;
import android.app.*;import android.os.*;import android.content.*;import android.graphics.Color;import android.print.*;import android.view.*;import android.view.inputmethod.InputMethodManager;import android.widget.*;import android.text.InputType;import java.text.*;import java.util.*;import android.database.Cursor;import java.io.*;
public class MainActivity extends Activity{
 DB db;LinearLayout root,content;boolean dark=false;Spinner typeSpinner,catSpinner;EditText amount,note,date;long editingId=-1;String BLUE="#1565C0";
 int dp(float x){return(int)(x*getResources().getDisplayMetrics().density+.5f);} TextView tv(String s,int z){TextView t=new TextView(this);t.setText(s);t.setTextSize(z);t.setPadding(dp(12),dp(8),dp(12),dp(8));return t;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);return b;}
 public void onCreate(Bundle b){super.onCreate(b);dark=getPreferences(0).getBoolean("dark",false);db=new DB(this);shell();showEntry();}
 void shell(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);TextView h=tv("আয়-ব্যয়",20);h.setTextColor(Color.WHITE);h.setGravity(Gravity.CENTER_VERTICAL);h.setBackgroundColor(Color.parseColor(BLUE));root.addView(h,new LinearLayout.LayoutParams(-1,dp(50)));
  LinearLayout nav=new LinearLayout(this);Button e=btn("এন্ট্রি"),l=btn("লেজার"),s=btn("সারাংশ"),d=btn("☾");nav.addView(e,new LinearLayout.LayoutParams(0,dp(50),1));nav.addView(l,new LinearLayout.LayoutParams(0,dp(50),1));nav.addView(s,new LinearLayout.LayoutParams(0,dp(50),1));nav.addView(d,new LinearLayout.LayoutParams(dp(58),dp(50)));root.addView(nav);
  ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(10),dp(8),dp(10),dp(20));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1));setContentView(root);
  e.setOnClickListener(v->showEntry());l.setOnClickListener(v->showLedger());s.setOnClickListener(v->showSummary());d.setOnClickListener(v->{dark=!dark;getPreferences(0).edit().putBoolean("dark",dark).apply();applyTheme();});applyTheme();}
 void applyTheme(){int bg=Color.parseColor(dark?"#121212":"#FFFFFF"),fg=Color.parseColor(dark?"#F5F5F5":"#222222");root.setBackgroundColor(bg);content.setBackgroundColor(bg);for(int i=0;i<content.getChildCount();i++){View v=content.getChildAt(i);if(v instanceof TextView)((TextView)v).setTextColor(fg);}}
 EditText field(String h){EditText e=new EditText(this);e.setHint(h);e.setTextSize(17);e.setSingleLine(true);e.setTextColor(dark?Color.WHITE:Color.BLACK);e.setHintTextColor(dark?0xFFBBBBBB:0xFF777777);return e;}
 void showEntry(){editingId=-1;content.removeAllViews();content.addView(tv("নতুন এন্ট্রি",22));typeSpinner=new Spinner(this);ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,new String[]{"ব্যয়","আয়"});typeSpinner.setAdapter(a);typeSpinner.setSelection(0);content.addView(typeSpinner,new LinearLayout.LayoutParams(-1,dp(52)));
  catSpinner=new Spinner(this);loadCats(2);content.addView(catSpinner,new LinearLayout.LayoutParams(-1,dp(52)));Button manage=btn("ক্যাটাগরি যোগ করুন");content.addView(manage);
  LinearLayout ar=new LinearLayout(this);amount=field("পরিমাণ");amount.setInputType(2|8192);Button calc=btn("🧮");calc.setTextSize(20);ar.addView(amount,new LinearLayout.LayoutParams(0,dp(60),1));ar.addView(calc,new LinearLayout.LayoutParams(dp(62),dp(60)));content.addView(ar);
  note=field("নোট (ঐচ্ছিক)");content.addView(note);date=field("তারিখ");date.setText(new SimpleDateFormat("yyyy-MM-dd",Locale.US).format(new Date()));content.addView(date);
  Button save=btn("সংরক্ষণ করুন");save.setTextSize(18);content.addView(save,new LinearLayout.LayoutParams(-1,dp(58)));TextView today=tv("আজকের মোট আয়: "+money(db.sum(1))+"\nআজকের মোট ব্যয়: "+money(db.sum(2)),15);content.addView(today);
  typeSpinner.setOnItemSelectedListener(new android.widget.AdapterView.OnItemSelectedListener(){public void onNothingSelected(android.widget.AdapterView<?>x){}public void onItemSelected(android.widget.AdapterView<?>x,View v,int p,long id){loadCats(p==0?2:1);}});
  calc.setOnClickListener(v->calculator());manage.setOnClickListener(v->addCategory());save.setOnClickListener(v->{String c=catSpinner.getSelectedItem()==null?"":catSpinner.getSelectedItem().toString();String am=amount.getText().toString().trim();if(am.isEmpty()){toast("পরিমাণ দিন");return;}db.add(typeSpinner.getSelectedItemPosition()==0?2:1,c,Double.parseDouble(am),note.getText().toString().trim(),date.getText().toString());toast("সংরক্ষণ হয়েছে");amount.setText("");note.setText("");});applyTheme();}
 void loadCats(int type){if(catSpinner==null)return;ArrayList<String>x=new ArrayList<>();Cursor c=db.categories(type);while(c.moveToNext())x.add(c.getString(0));c.close();ArrayAdapter<String>a=new ArrayAdapter<>(this,android.R.layout.simple_spinner_dropdown_item,x);catSpinner.setAdapter(a);}
 void addCategory(){final EditText e=field("নতুন ক্যাটাগরি");new AlertDialog.Builder(this).setTitle("ক্যাটাগরি যোগ করুন").setView(e).setNegativeButton("বাতিল",null).setPositiveButton("যোগ", (d,w)->{String n=e.getText().toString().trim();if(!n.isEmpty()){db.addCategory(n,typeSpinner.getSelectedItemPosition()==0?2:1);loadCats(typeSpinner.getSelectedItemPosition()==0?2:1);}}).show();}
 void calculator(){final EditText x=field("0");x.setText("0");LinearLayout box=new LinearLayout(this);box.setOrientation(LinearLayout.VERTICAL);box.addView(x);String[]ks={"7","8","9","÷","4","5","6","×","1","2","3","−","0",".","C","+","="};LinearLayout r=null;int n=0;for(String k:ks){if(n%4==0){r=new LinearLayout(this);box.addView(r);}Button b=btn(k);r.addView(b,new LinearLayout.LayoutParams(0,dp(46),1));final String q=k;b.setOnClickListener(v->{String z=x.getText().toString();if(q.equals("C"))x.setText("0");else if(q.equals("=")){try{x.setText(""+eval(z));}catch(Exception e){x.setText("0");}}else{x.setText((z.equals("0")&&!q.equals(".")?"":z)+q);}});n++;}new AlertDialog.Builder(this).setTitle("ক্যালকুলেটর").setView(box).setNegativeButton("বন্ধ",null).setPositiveButton("পরিমাণে দিন",(d,w)->amount.setText(x.getText())).show();}
 double eval(String s){s=s.replace("×","*").replace("÷","/").replace("−","-");double total=0;String[] plus=s.split("\\+");for(String p:plus){double v=1;String[] mul=p.split("\\*");for(String m:mul){if(m.contains("/")){String[]q=m.split("/");double z=Double.parseDouble(q[0]);for(int i=1;i<q.length;i++)z/=Double.parseDouble(q[i]);v*=z;}else v*=Double.parseDouble(m);}total+=v;}return total;}
 String money(double x){return String.format(Locale.US,"৳ %.2f",x);} void showLedger(){content.removeAllViews();content.addView(tv("লেজার",22));Cursor c=db.all();while(c.moveToNext()){long id=c.getLong(0);int type=c.getInt(1);TextView row=tv(c.getString(5)+"  •  "+(type==1?"আয়":"ব্যয়")+"  •  "+c.getString(2)+"\n"+money(c.getDouble(3))+(c.getString(4).isEmpty()?"":"  |  "+c.getString(4)),15);row.setBackgroundColor(type==1?0xFFE8F5E9:0xFFFFEBEE);row.setOnLongClickListener(v->{new AlertDialog.Builder(this).setTitle("এন্ট্রি").setItems(new String[]{"ডিলিট"},(d,w)->{db.delete(id);showLedger();}).show();return true;});content.addView(row,new LinearLayout.LayoutParams(-1,dp(72)));}c.close();Button p=btn("লেজার প্রিন্ট");content.addView(p);p.setOnClickListener(v->printHtml(ledgerHtml(),"লেজার"));Button backup=btn("ব্যাকআপ ফাইল তৈরি করুন");content.addView(backup);backup.setOnClickListener(v->backup());Button restore=btn("ব্যাকআপ Restore");content.addView(restore);restore.setOnClickListener(v->restore());applyTheme();}
 void showSummary(){content.removeAllViews();content.addView(tv("সারাংশ",22));double i=db.sum(1),e=db.sum(2);content.addView(tv("মোট আয়\n"+money(i)+"\n\nমোট ব্যয়\n"+money(e)+"\n\nব্যালেন্স\n"+money(i-e),20));content.addView(tv("খাতভিত্তিক ব্যয়",19));Cursor c=db.expenseByCat();while(c.moveToNext())content.addView(tv(c.getString(0)+" — "+money(c.getDouble(1)),16));c.close();Button p=btn("সারাংশ প্রিন্ট");content.addView(p);p.setOnClickListener(v->printHtml(summaryHtml(),"সারাংশ"));Button clear=btn("সব ডাটা মুছুন");content.addView(clear);clear.setOnClickListener(v->new AlertDialog.Builder(this).setTitle("সতর্কতা").setMessage("সব ডাটা মুছে যাবে।").setNegativeButton("না",null).setPositiveButton("হ্যাঁ",(d,w)->{db.clearAll();showSummary();}).show());applyTheme();}
 String ledgerHtml(){StringBuilder h=new StringBuilder("<html><meta charset='utf-8'><body><h2>আয়-ব্যয় লেজার</h2><table border='1' cellpadding='6'><tr><th>তারিখ</th><th>ধরন</th><th>ক্যাটাগরি</th><th>পরিমাণ</th><th>নোট</th></tr>");Cursor c=db.all();while(c.moveToNext())h.append("<tr><td>").append(c.getString(5)).append("</td><td>").append(c.getInt(1)==1?"আয়":"ব্যয়").append("</td><td>").append(c.getString(2)).append("</td><td>").append(money(c.getDouble(3))).append("</td><td>").append(c.getString(4)).append("</td></tr>");c.close();return h.append("</table><p>মোট আয়: ").append(money(db.sum(1))).append("<br>মোট ব্যয়: ").append(money(db.sum(2))).append("<br>ব্যালেন্স: ").append(money(db.sum(1)-db.sum(2))).append("</p></body></html>").toString();}
 String summaryHtml(){return "<html><meta charset='utf-8'><body><h2>আয়-ব্যয় সারাংশ</h2><p>মোট আয়: "+money(db.sum(1))+"</p><p>মোট ব্যয়: "+money(db.sum(2))+"</p><p>ব্যালেন্স: "+money(db.sum(1)-db.sum(2))+"</p></body></html>";}
 void printHtml(String h,String n){((PrintManager)getSystemService(PRINT_SERVICE)).print(n,new WebPrintAdapter(this,h),new PrintAttributes.Builder().setMediaSize(PrintAttributes.MediaSize.ISO_A4).build());}
 void backup(){try{File f=new File(getExternalFilesDir(null),"income-expense-backup.csv");PrintWriter p=new PrintWriter(f);p.println("type,category,amount,note,date");Cursor c=db.all();while(c.moveToNext())p.println(c.getInt(1)+","+csv(c.getString(2))+","+c.getDouble(3)+","+csv(c.getString(4))+","+c.getString(5));c.close();p.close();toast("Backup saved: "+f.getAbsolutePath());}catch(Exception e){toast("Backup failed");}}
 String csv(String s){return "\""+s.replace("\"","\"\"")+"\"";}void restore(){toast("Restore: backup import can be added with Android file picker in the next patch.");}
 void toast(String s){Toast.makeText(this,s,Toast.LENGTH_LONG).show();}
}